service: serverless-http-api-typescript

provider:
  name: aws
  runtime: nodejs18.x

layers:
  cryptoLayer:
    path: layers/nodejs
    compatibleRuntimes:
      - nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
    layers:
      - { Ref: CryptoLayerLambdaLayer }